from app.domain.systems.models import CommercialRuleDefinition
from app.domain.systems.product_templates import FRONTLIT_TEMPLATE

COMMERCIAL_RULES: dict[str, CommercialRuleDefinition] = {
    "face_area_rule": CommercialRuleDefinition(
        rule_code="face_area_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="face",
        display_name="Fata litere — suprafata",
        commercial_basis="mp",
        required_inputs=["face_area_m2", "face_material"],
        required_owner_decisions=["face_material"],
        output_line_type="material_area",
        blocking_behavior="blocking_if_missing",
    ),
    "face_cut_rule": CommercialRuleDefinition(
        rule_code="face_cut_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="face",
        display_name="Fata litere — debitare",
        commercial_basis="ml",
        commercial_basis_alternatives=["included"],
        required_inputs=["cut_length_ml"],
        output_line_type="operation_cut",
        blocking_behavior="manual_owner_review",
        notes="manual_owner_review when cut_length_ml missing",
    ),
    "return_cant_rule": CommercialRuleDefinition(
        rule_code="return_cant_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="return_cant",
        display_name="Cant / laterale",
        commercial_basis="ml",
        required_inputs=["perimeter_ml", "return_depth_mm", "return_material"],
        required_owner_decisions=["return_material"],
        output_line_type="material_length",
        blocking_behavior="blocking_if_missing",
    ),
    "back_panel_rule": CommercialRuleDefinition(
        rule_code="back_panel_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="back",
        display_name="Spate litere",
        commercial_basis="mp",
        required_inputs=["back_area_m2", "back_material"],
        required_owner_decisions=["back_material"],
        output_line_type="material_area",
        blocking_behavior="blocking_if_missing",
    ),
    "led_modules_rule": CommercialRuleDefinition(
        rule_code="led_modules_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="led",
        display_name="Module LED",
        commercial_basis="buc",
        required_inputs=["estimated_led_count", "led_density_policy"],
        required_owner_decisions=["led_type", "led_density_policy"],
        output_line_type="component_count",
        blocking_behavior="blocking_if_missing",
        notes="Alternative path: led_area_m2 + led_density_policy",
    ),
    "psu_rule": CommercialRuleDefinition(
        rule_code="psu_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="psu",
        display_name="Sursa alimentare",
        commercial_basis="buc",
        required_inputs=["estimated_power_w", "psu_policy"],
        required_owner_decisions=["psu_policy"],
        output_line_type="component_count",
        blocking_behavior="blocking_if_missing",
    ),
    "finish_rule": CommercialRuleDefinition(
        rule_code="finish_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="finish",
        display_name="Finisaj",
        commercial_basis="mp",
        required_inputs=["finish_area_m2", "finish_type"],
        required_owner_decisions=["finish_type"],
        output_line_type="finish_area",
        blocking_behavior="blocking_if_missing",
    ),
    "support_rule": CommercialRuleDefinition(
        rule_code="support_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="support",
        display_name="Suport / structura",
        commercial_basis="manual_owner_review",
        commercial_basis_alternatives=["mp", "ml"],
        required_inputs=["support_required", "support_type"],
        required_owner_decisions=["support_required_decision", "support_type_decision"],
        output_line_type="support_structure",
        blocking_behavior="blocking_if_missing",
        notes="Blocking when support_required is true and support_type missing",
    ),
    "mounting_rule": CommercialRuleDefinition(
        rule_code="mounting_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="mounting",
        display_name="Montaj / prindere",
        commercial_basis="service_fixed",
        commercial_basis_alternatives=["external_service", "manual_owner_review"],
        required_inputs=["mounting_required", "mounting_type"],
        required_owner_decisions=["mounting_required_decision", "mounting_type_decision"],
        output_line_type="installation_service",
        blocking_behavior="blocking_if_missing",
        notes="Blocking when mounting_required is true and mounting_type missing",
    ),
    "packaging_rule": CommercialRuleDefinition(
        rule_code="packaging_rule",
        template_code=FRONTLIT_TEMPLATE,
        component_code="packaging",
        display_name="Ambalare / livrare",
        commercial_basis="service_fixed",
        commercial_basis_alternatives=["included", "manual_owner_review"],
        required_inputs=["packaging_required", "package_size_class"],
        required_owner_decisions=["packaging_required_decision", "delivery_policy"],
        output_line_type="logistics_service",
        blocking_behavior="blocking_if_missing",
        notes="Blocking when packaging_required is true",
    ),
}
