from app.domain.systems.models import ComponentDefinition
from app.domain.systems.product_templates import FAMILY_CODE, FRONTLIT_TEMPLATE

COMPONENTS: dict[str, ComponentDefinition] = {
    "face": ComponentDefinition(
        component_code="face",
        template_code=FRONTLIT_TEMPLATE,
        family_code=FAMILY_CODE,
        display_name="Fata litere",
        role="fata litere",
        required_measurements=[
            "artwork_width_mm",
            "artwork_height_mm",
            "face_area_m2",
        ],
        required_owner_decisions=["face_material", "face_finish"],
        notes="cut_length_ml optional/later via face_cut_rule",
    ),
    "return_cant": ComponentDefinition(
        component_code="return_cant",
        template_code=FRONTLIT_TEMPLATE,
        family_code=FAMILY_CODE,
        display_name="Laterale / cant",
        role="laterale/cant",
        required_measurements=["perimeter_ml", "return_depth_mm"],
        required_owner_decisions=["return_material", "return_finish"],
    ),
    "back": ComponentDefinition(
        component_code="back",
        template_code=FRONTLIT_TEMPLATE,
        family_code=FAMILY_CODE,
        display_name="Spate litere",
        role="spate litere",
        required_measurements=["back_area_m2"],
        required_owner_decisions=["back_material"],
    ),
    "led": ComponentDefinition(
        component_code="led",
        template_code=FRONTLIT_TEMPLATE,
        family_code=FAMILY_CODE,
        display_name="Iluminare LED",
        role="iluminare",
        required_measurements=["estimated_led_count"],
        required_owner_decisions=["led_type", "light_color", "led_density_policy"],
        notes="led_area_m2 alternative input path via led_density_policy",
    ),
    "psu": ComponentDefinition(
        component_code="psu",
        template_code=FRONTLIT_TEMPLATE,
        family_code=FAMILY_CODE,
        display_name="Sursa alimentare",
        role="sursa alimentare",
        required_measurements=["estimated_power_w"],
        required_owner_decisions=["psu_policy"],
    ),
    "finish": ComponentDefinition(
        component_code="finish",
        template_code=FRONTLIT_TEMPLATE,
        family_code=FAMILY_CODE,
        display_name="Finisaj vizual",
        role="finisaj vizual",
        required_measurements=["finish_area_m2"],
        required_owner_decisions=["finish_type"],
    ),
    "support": ComponentDefinition(
        component_code="support",
        template_code=FRONTLIT_TEMPLATE,
        family_code=FAMILY_CODE,
        display_name="Suport / structura",
        role="suport/structura",
        required_measurements=["support_area_m2", "support_length_ml"],
        required_owner_decisions=["support_required_decision", "support_type_decision"],
        notes="Physical backing/support/structure — distinct from mounting",
    ),
    "mounting": ComponentDefinition(
        component_code="mounting",
        template_code=FRONTLIT_TEMPLATE,
        family_code=FAMILY_CODE,
        display_name="Montaj / prindere",
        role="montaj/prindere",
        required_measurements=["installation_complexity"],
        required_owner_decisions=["mounting_required_decision", "mounting_type_decision"],
        notes="Installation/fixing method/service — distinct from support",
    ),
    "packaging": ComponentDefinition(
        component_code="packaging",
        template_code=FRONTLIT_TEMPLATE,
        family_code=FAMILY_CODE,
        display_name="Ambalare / livrare",
        role="ambalare/livrare",
        required_measurements=["package_size_class"],
        required_owner_decisions=["packaging_required_decision", "delivery_policy"],
    ),
}
