from app.domain.systems.models import IntakeFieldDefinition
from app.domain.systems.product_templates import FRONTLIT_TEMPLATE, NON_LIT_TEMPLATE

INTAKE_FIELDS: dict[str, IntakeFieldDefinition] = {
    "template_code": IntakeFieldDefinition(
        field_code="template_code",
        label="Template produs",
        field_type="string",
        required=True,
        source="system_default",
        applies_to_template_codes=[FRONTLIT_TEMPLATE, NON_LIT_TEMPLATE],
        feeds_rules=[],
    ),
    "artwork_width_mm": IntakeFieldDefinition(
        field_code="artwork_width_mm",
        label="Latime artwork (mm)",
        field_type="number",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE, NON_LIT_TEMPLATE],
        feeds_rules=["face_area_rule"],
        validation={"gt": 0},
    ),
    "artwork_height_mm": IntakeFieldDefinition(
        field_code="artwork_height_mm",
        label="Inaltime artwork (mm)",
        field_type="number",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE, NON_LIT_TEMPLATE],
        feeds_rules=["face_area_rule"],
        validation={"gt": 0},
    ),
    "face_area_m2": IntakeFieldDefinition(
        field_code="face_area_m2",
        label="Suprafata fata (m2)",
        field_type="number",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["face_area_rule"],
        validation={"gt": 0},
    ),
    "back_area_m2": IntakeFieldDefinition(
        field_code="back_area_m2",
        label="Suprafata spate (m2)",
        field_type="number",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["back_panel_rule"],
        validation={"gt": 0},
    ),
    "perimeter_ml": IntakeFieldDefinition(
        field_code="perimeter_ml",
        label="Perimetru litere (ml)",
        field_type="number",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["return_cant_rule"],
        validation={"gt": 0},
    ),
    "return_depth_mm": IntakeFieldDefinition(
        field_code="return_depth_mm",
        label="Adancime cant (mm)",
        field_type="number",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["return_cant_rule"],
        validation={"gt": 0},
    ),
    "finish_area_m2": IntakeFieldDefinition(
        field_code="finish_area_m2",
        label="Suprafata finisaj (m2)",
        field_type="number",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["finish_rule"],
        validation={"gt": 0},
    ),
    "estimated_led_count": IntakeFieldDefinition(
        field_code="estimated_led_count",
        label="Numar estimat module LED",
        field_type="integer",
        required=False,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["led_modules_rule"],
        validation={"ge": 0},
        notes="Required unless led_area_m2 + led_density_policy path used (Phase 2)",
    ),
    "estimated_power_w": IntakeFieldDefinition(
        field_code="estimated_power_w",
        label="Putere estimata (W)",
        field_type="number",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["psu_rule"],
        validation={"gt": 0},
    ),
    "support_required": IntakeFieldDefinition(
        field_code="support_required",
        label="Suport necesar",
        field_type="boolean",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["support_rule"],
    ),
    "support_type": IntakeFieldDefinition(
        field_code="support_type",
        label="Tip suport",
        field_type="enum",
        required=False,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["support_rule"],
        notes="Required when support_required is true",
    ),
    "mounting_required": IntakeFieldDefinition(
        field_code="mounting_required",
        label="Montaj necesar",
        field_type="boolean",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["mounting_rule"],
    ),
    "mounting_type": IntakeFieldDefinition(
        field_code="mounting_type",
        label="Tip montaj",
        field_type="enum",
        required=False,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["mounting_rule"],
        notes="Required when mounting_required is true",
    ),
    "packaging_required": IntakeFieldDefinition(
        field_code="packaging_required",
        label="Ambalare necesara",
        field_type="boolean",
        required=True,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["packaging_rule"],
    ),
    "package_size_class": IntakeFieldDefinition(
        field_code="package_size_class",
        label="Clasa dimensiune ambalare",
        field_type="enum",
        required=False,
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["packaging_rule"],
        notes="Required when packaging_required is true",
    ),
}
