from app.domain.systems.models import OwnerDecisionDefinition
from app.domain.systems.product_templates import FRONTLIT_TEMPLATE

OWNER_DECISIONS: dict[str, OwnerDecisionDefinition] = {
    "face_material": OwnerDecisionDefinition(
        decision_code="face_material",
        label="Material fata",
        decision_type="material",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["face_area_rule"],
        allowed_values=["acrylic_clear", "acrylic_white", "acrylic_colored"],
    ),
    "face_finish": OwnerDecisionDefinition(
        decision_code="face_finish",
        label="Finisaj fata",
        decision_type="finish",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["face_area_rule"],
        allowed_values=["mat", "gloss", "satin"],
    ),
    "return_material": OwnerDecisionDefinition(
        decision_code="return_material",
        label="Material cant",
        decision_type="material",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["return_cant_rule"],
        allowed_values=["aluminum_brushed", "aluminum_painted", "pvc"],
    ),
    "return_finish": OwnerDecisionDefinition(
        decision_code="return_finish",
        label="Finisaj cant",
        decision_type="finish",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["return_cant_rule"],
        allowed_values=["standard", "ral_custom"],
    ),
    "back_material": OwnerDecisionDefinition(
        decision_code="back_material",
        label="Material spate",
        decision_type="material",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["back_panel_rule"],
        allowed_values=["pvc_white", "pvc_black", "forex"],
    ),
    "led_type": OwnerDecisionDefinition(
        decision_code="led_type",
        label="Tip LED",
        decision_type="enum_choice",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["led_modules_rule"],
        allowed_values=["module_standard", "module_premium", "strip"],
    ),
    "light_color": OwnerDecisionDefinition(
        decision_code="light_color",
        label="Culoare lumina",
        decision_type="enum_choice",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["led_modules_rule"],
        allowed_values=["white_6500k", "warm_3000k", "rgb"],
    ),
    "led_density_policy": OwnerDecisionDefinition(
        decision_code="led_density_policy",
        label="Politica densitate LED",
        decision_type="policy",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["led_modules_rule"],
        allowed_values=["standard", "high_density", "owner_defined"],
    ),
    "psu_policy": OwnerDecisionDefinition(
        decision_code="psu_policy",
        label="Politica sursa alimentare",
        decision_type="policy",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["psu_rule"],
        allowed_values=["auto_class", "manual_class", "redundancy"],
    ),
    "finish_type": OwnerDecisionDefinition(
        decision_code="finish_type",
        label="Tip finisaj",
        decision_type="finish",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["finish_rule"],
        allowed_values=["foil", "paint", "none"],
    ),
    "support_required_decision": OwnerDecisionDefinition(
        decision_code="support_required_decision",
        label="Confirmare suport necesar",
        decision_type="boolean_gate",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["support_rule"],
        allowed_values=["yes", "no"],
    ),
    "support_type_decision": OwnerDecisionDefinition(
        decision_code="support_type_decision",
        label="Tip suport (decizie owner)",
        decision_type="enum_choice",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["support_rule"],
        allowed_values=["frame", "panel", "custom"],
        notes="Required when support is required",
    ),
    "mounting_required_decision": OwnerDecisionDefinition(
        decision_code="mounting_required_decision",
        label="Confirmare montaj necesar",
        decision_type="boolean_gate",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["mounting_rule"],
        allowed_values=["yes", "no"],
    ),
    "mounting_type_decision": OwnerDecisionDefinition(
        decision_code="mounting_type_decision",
        label="Tip montaj (decizie owner)",
        decision_type="enum_choice",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["mounting_rule"],
        allowed_values=["wall_studs", "spacers", "external_contractor"],
    ),
    "packaging_required_decision": OwnerDecisionDefinition(
        decision_code="packaging_required_decision",
        label="Confirmare ambalare necesara",
        decision_type="boolean_gate",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["packaging_rule"],
        allowed_values=["yes", "no"],
    ),
    "delivery_policy": OwnerDecisionDefinition(
        decision_code="delivery_policy",
        label="Politica livrare",
        decision_type="policy",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["packaging_rule"],
        allowed_values=["pickup", "local_delivery", "national_courier"],
    ),
    "back_cut_basis": OwnerDecisionDefinition(
        decision_code="back_cut_basis",
        label="Baza comerciala debitare spate",
        decision_type="enum_choice",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["back_panel_rule"],
        allowed_values=["m2", "ml"],
        required=False,
        notes="Legacy: DEBITARE_SPATE_BASIS_ML_VS_M2 — optional until back rule uses alternate quantity path.",
    ),
    "forex_template_price": OwnerDecisionDefinition(
        decision_code="forex_template_price",
        label="Pret comercial sablon Forex",
        decision_type="policy",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["sablon_montaj_rule"],
        allowed_values=["approved", "pending"],
        required=False,
        notes="Legacy: SABLON_FOREX_COMMERCIAL_PRICE — gates forex sablon line pricing.",
    ),
    "packaging_commercial": OwnerDecisionDefinition(
        decision_code="packaging_commercial",
        label="Regula comerciala ambalare",
        decision_type="policy",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["packaging_rule"],
        allowed_values=["fixed", "included", "pending"],
        required=False,
        notes="Legacy: AMBALARE_COMMERCIAL_RULE.",
    ),
    "site_mount_commercial": OwnerDecisionDefinition(
        decision_code="site_mount_commercial",
        label="Regula comerciala montaj santier",
        decision_type="policy",
        applies_to_template_codes=[FRONTLIT_TEMPLATE],
        feeds_rules=["mounting_rule"],
        allowed_values=["fixed", "external", "pending"],
        required=False,
        notes="Legacy: MONTAJ_COMMERCIAL_RULE — optional site mount.",
    ),
}
